package se.quizmaniacs.Commands;

/**
 * Created by LeoAsp on 2017-01-30.
 */

public enum CommandType {
    SETNICK, UPDATELOBBYLIST, GETLOBBYLIST, GETCATEGORIES, UPDATENICK, UPDATEROOM ,CREATEROOM, PLAYERREADY, PLAYERLEAVE, GETROOM, UPDATEROOMNAME, PLAYERNOTREADY, PLAYERJOIN
}
