package se.quizmaniacs.Commands;


public enum CommandType {
    SETNICK, UPDATELOBBYLIST, GETLOBBYLIST, GETCATEGORIES, UPDATENICK, UPDATEROOM, CREATEROOM, PLAYERREADY, PLAYERLEAVE, GETROOM, UPDATEROOMNAME, PLAYERNOTREADY, UPDATEROOMPLAYERLIST, PLAYERJOIN, SENDMESSAGE, PLAYERSENDMESSAGE
}
